apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.serviceName }}-dev
  namespace: argocd
spec:
  project: paved-road
  source:
    repoURL: https://github.com/salman-frs/paved-road-aws.git
    targetRevision: main
    path: services/${{ values.serviceName }}/chart
    helm:
      valueFiles:
        - ../../../gitops/dev/${{ values.serviceName }}/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.serviceName }}-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
