apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ printf "%s-%s" .Values.service.name .Values.environment }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}
  ports:
    - name: http
      port: 80
      targetPort: http
